/**
 * What Android's Auto Backup takes to Google Drive and to a new phone (ADR-0048).
 *
 * expo-secure-store ships rules that include only shared preferences, and a rule with
 * an <include> backs up nothing else — so the database, which is every session, habit
 * and streak, never left the phone and a new Android phone started from zero. These
 * rules replace them (the plugin runs with `configureAndroidBackup: false`):
 *
 * - `database`: vesper.db with its -wal and -shm, which only make sense together.
 * - `sharedpref`, minus three files:
 *   - SecureStore: the circle secret, sealed by a Keystore key that never leaves the
 *     phone. Restored elsewhere it cannot be opened; the backup key is how it travels.
 *     Excluded under both spellings, because Expo's own rule leaves out `.xml`.
 *   - vesper_blocking and vesper_windows: the blocking plan and the routine windows.
 *     They are this phone's state, rebuilt from the database the first time JS runs,
 *     and BootReceiver would arm the old phone's windows on the new one before that.
 *
 * Android 11 and lower read `full-backup-content`; 12 and higher read
 * `data-extraction-rules`, once for the cloud and once for a cable or tap transfer.
 */

const fs = require('fs');
const path = require('path');
const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('expo/config-plugins');

const BACKUP_RULES = 'vesper_backup_rules';
const EXTRACTION_RULES = 'vesper_data_extraction_rules';

const EXCLUDED_PREFS = ['SecureStore', 'SecureStore.xml', 'vesper_blocking.xml', 'vesper_windows.xml'];

function rules(indent) {
  const pad = ' '.repeat(indent);
  return [
    `${pad}<include domain="database" path="."/>`,
    `${pad}<include domain="sharedpref" path="."/>`,
    ...EXCLUDED_PREFS.map((file) => `${pad}<exclude domain="sharedpref" path="${file}"/>`),
  ].join('\n');
}

const FULL_BACKUP_CONTENT = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidBackup.js (ADR-0048). Android 11 and lower. -->
<full-backup-content>
${rules(2)}
</full-backup-content>
`;

const DATA_EXTRACTION_RULES = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidBackup.js (ADR-0048). Android 12 and higher. -->
<data-extraction-rules>
  <cloud-backup>
${rules(4)}
  </cloud-backup>
  <device-transfer>
${rules(4)}
  </device-transfer>
</data-extraction-rules>
`;

function withBackupRuleFiles(config) {
  return withDangerousMod(config, [
    'android',
    async (mod) => {
      const dir = path.join(mod.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res', 'xml');
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, `${BACKUP_RULES}.xml`), FULL_BACKUP_CONTENT);
      fs.writeFileSync(path.join(dir, `${EXTRACTION_RULES}.xml`), DATA_EXTRACTION_RULES);
      return mod;
    },
  ]);
}

function withBackupManifest(config) {
  return withAndroidManifest(config, (mod) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(mod.modResults);
    application.$['android:allowBackup'] = 'true';
    application.$['android:fullBackupContent'] = `@xml/${BACKUP_RULES}`;
    application.$['android:dataExtractionRules'] = `@xml/${EXTRACTION_RULES}`;
    return mod;
  });
}

module.exports = function withAndroidBackup(config) {
  return withBackupManifest(withBackupRuleFiles(config));
};
